# Data science with xarray

Hello and welcome to your intro to `xarray` for data science as part of NCI's Parallel Python data science course.

This notebook is designed to cover the fundamentals of `xarray` highlighting some similarities with tools you have already been introduced to such as `NumPy` and `CuPy` and some of the advantages of using `xarray`.


## Intro

First of all what is `xarray`? `xarray` is a project that came out of climate and geophysics research, recognising the need for rapid, scalable and easily manipulated N dimensional array data **with labels and metadata**. 

But wait, doesn't `NumPy` provide an N Dimensional array? Yes it does, but `xarray` provides the ability to use labelled and metadata rich arrays, providing to quote the manual a " more intuitive, more concise, and less error-prone developer experience"

This is done by providing a label based API that simplifies a lot of the manual book keeping of working with `numpy` arrays directly.

No longer will you forget what experiment this data came from, what that tensor dimension was, or what array position corresponded to with time point! Even better these, augmented N dimensional arrays can be combined to make massive datasets, enabling analysis of huge volumes of data. It's all there in  the one datastructure that can be easily stored and shared, as is done on a massive scale using `xarray` in the climate modelling, geophysics, and astrophysics communities to name just a few. 


Alright, lets jump in!

## Crash course

In [1]:
# lets import xarray and numpy
import xarray as xr
import numpy as np

The `DataArray` is the `xarray` equivalent of the `numpy` `ndarray` and will be the first focus of our intro. Lets make a 2 x 3 DataArray using a numpy array, so we can get the hang of how to work with it. 

In [2]:
inp = np.arange(6).reshape(2,3)
data = xr.DataArray(inp, dims=("x", "y"))
data

<xarray.DataArray (x: 2, y: 3)>
array([[0, 1, 2],
       [3, 4, 5]])
Dimensions without coordinates: x, y

We can see that our data array looks a lot like a numpy array, but with two labelled dimensions `x` and `y`. We can access our values directly using the `values` attribute as shown below. 

In [3]:
data.values

array([[0, 1, 2],
       [3, 4, 5]])

We can also access our dimensions using the `dims` attribute as shown below

In [4]:
data.dims

('x', 'y')

The eagle eyed amongst you may have  spotted the `coords` attribute. This is used to associate a value along a particular axis with another value, that could for example correspond to the time or location it was measured. The possibilities are only limited by your imagination

We set our `coords` using a dictionary corresponding to the `coords` along a particular axis.

In [5]:
coords = {"x":[10,20], "y":[0.1, 0.2, 0.3]}
data = data.assign_coords(coords)

**Notice the detail above**, we had to assign our `DataArray` to a new object (in this case we overwrote `data`) for our change to persist. This pattern will be familiar to those who use `pandas`.


## Indexing

Okay cool, how can we access the data in our array? We can use four kinds of slicing. 

* Numpy like using integer locations
* using `loc` like in pandas
* using an integer select (`isel`), combining a dimension name and integer label
* using a selection (`sel`) based on coordinate combining a dimension name and coordinate value

The following selections all give the same set of values, those at `x=10`:

Numpy like using array indexing:

In [6]:
data[0, :]

<xarray.DataArray (y: 3)>
array([0, 1, 2])
Coordinates:
    x        int64 10
  * y        (y) float64 0.1 0.2 0.3

Pandas like using `loc`

In [7]:
data.loc[10]

<xarray.DataArray (y: 3)>
array([0, 1, 2])
Coordinates:
    x        int64 10
  * y        (y) float64 0.1 0.2 0.3

An xarray integer selection

In [8]:
data.isel(x=0)

<xarray.DataArray (y: 3)>
array([0, 1, 2])
Coordinates:
    x        int64 10
  * y        (y) float64 0.1 0.2 0.3

An xarray selection

In [9]:
data.sel(x=10)

<xarray.DataArray (y: 3)>
array([0, 1, 2])
Coordinates:
    x        int64 10
  * y        (y) float64 0.1 0.2 0.3

When dealing with a complicated multidimensional dataset, I and the creators of `xarray` would argue that the last two are simple and powerful.

Note that we can also use `pandas` style `DataArray.dim` indexing to access a given dimension eg:


In [10]:
data.x

<xarray.DataArray 'x' (x: 2)>
array([10, 20])
Coordinates:
  * x        (x) int64 10 20

aggregation operations can also use dimension labels eg:

In [11]:
data.mean(dim="x")

<xarray.DataArray (y: 3)>
array([1.5, 2.5, 3.5])
Coordinates:
  * y        (y) float64 0.1 0.2 0.3

## Metadata

When dealing with complex data another advantage of `xarray` is metadata. Using the `.attrs`  `dict` attribute of `DataArray` we can associate any arbitrary field with our array data. For example lets label our current dataset:


In [12]:
data.attrs["long_name"] = "random array"
data.attrs["units"] = "rad/second"
data.attrs["description"] = "A random variable created as an example."
data.attrs["arbitrary"] = "arbitrary"


We can also associate our dimensions with metadata. For example lets add some metadata with our `x` dimension. 

Note here that we use pandas style `data.dim` accessing as demonstrated above.

In [13]:
data.x.attrs["units"] = "x units"
data.x.attrs["name"] = "name of x dimension"

Of course, just like a numpy array we can do broadcasted operations accross the whole array

In [14]:
data += 100
data

<xarray.DataArray (x: 2, y: 3)>
array([[100, 101, 102],
       [103, 104, 105]])
Coordinates:
  * x        (x) int64 10 20
  * y        (y) float64 0.1 0.2 0.3
Attributes:
    long_name:    random array
    units:        rad/second
    description:  A random variable created as an example.
    arbitrary:    arbitrary

And use many of the standard numpy style shortcuts such as `.T` 

In [15]:
data.T

<xarray.DataArray (y: 3, x: 2)>
array([[100, 103],
       [101, 104],
       [102, 105]])
Coordinates:
  * x        (x) int64 10 20
  * y        (y) float64 0.1 0.2 0.3
Attributes:
    long_name:    random array
    units:        rad/second
    description:  A random variable created as an example.
    arbitrary:    arbitrary

## Broadcasting, operations and labelled dimensions

A fantastic feature of xarray is that operations are dimension specific. Let me show you what I mean.

We are going to make three arrays for demonstration purposes. Array `x` and `y` have different `dims` while `x` and `z` share the `x` dimension.

In [16]:
# has x as dimension
x = xr.DataArray(np.arange(10), dims="x", coords= {"x": np.arange(10)/10})

# has y as dimension
y = xr.DataArray(np.arange(3), dims="y", coords = {"y": np.arange(3)/10})

# has x dimension
z = xr.DataArray(np.arange(3), dims="x", coords = {"x": np.arange(3)/10})

So what happens when I do an operation on arrays with non-matching dimensions?


In [17]:
print(x)
print(y)
print(z)


<xarray.DataArray (x: 10)>
array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
Coordinates:
  * x        (x) float64 0.0 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9
<xarray.DataArray (y: 3)>
array([0, 1, 2])
Coordinates:
  * y        (y) float64 0.0 0.1 0.2
<xarray.DataArray (x: 3)>
array([0, 1, 2])
Coordinates:
  * x        (x) float64 0.0 0.1 0.2


In [18]:
# result broadcast
result = x*y
result

<xarray.DataArray (x: 10, y: 3)>
array([[ 0,  0,  0],
       [ 0,  1,  2],
       [ 0,  2,  4],
       [ 0,  3,  6],
       [ 0,  4,  8],
       [ 0,  5, 10],
       [ 0,  6, 12],
       [ 0,  7, 14],
       [ 0,  8, 16],
       [ 0,  9, 18]])
Coordinates:
  * x        (x) float64 0.0 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9
  * y        (y) float64 0.0 0.1 0.2

Thats interesting! We actually get an **outer product** (tensor product for more than two matching dimensions) formed by broadcasting accross the non-matching dimensions.  

When dimensions and coordinates match, we can easily broadcast accross those instead.

In [19]:
# result broadcast on matching dimension and coordinates
result = x*z
result


<xarray.DataArray (x: 3)>
array([0, 1, 4])
Coordinates:
  * x        (x) float64 0.0 0.1 0.2

The net result of all of this is that we don't need to manually keep track of dimension ordering, indexing and alignment of our coordinates as you would have to do in numpy and don't have to pad arrays with dummy data.

As an example of this, lets multiply our array by its transpose, noting that it is not a square matrix.

In [20]:
ten_by_three = x*y
ten_by_three

<xarray.DataArray (x: 10, y: 3)>
array([[ 0,  0,  0],
       [ 0,  1,  2],
       [ 0,  2,  4],
       [ 0,  3,  6],
       [ 0,  4,  8],
       [ 0,  5, 10],
       [ 0,  6, 12],
       [ 0,  7, 14],
       [ 0,  8, 16],
       [ 0,  9, 18]])
Coordinates:
  * x        (x) float64 0.0 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9
  * y        (y) float64 0.0 0.1 0.2

In [21]:
ten_by_three_transpose = ten_by_three.T
ten_by_three_transpose

<xarray.DataArray (y: 3, x: 10)>
array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18]])
Coordinates:
  * x        (x) float64 0.0 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9
  * y        (y) float64 0.0 0.1 0.2

In [22]:
result = ten_by_three*ten_by_three.T
result

<xarray.DataArray (x: 10, y: 3)>
array([[  0,   0,   0],
       [  0,   1,   4],
       [  0,   4,  16],
       [  0,   9,  36],
       [  0,  16,  64],
       [  0,  25, 100],
       [  0,  36, 144],
       [  0,  49, 196],
       [  0,  64, 256],
       [  0,  81, 324]])
Coordinates:
  * x        (x) float64 0.0 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9
  * y        (y) float64 0.0 0.1 0.2

here, xarray took care of aligning our dimensions based on **dimension labels** even though the order of dimensions was reversed in our transpose.

This is not possible in numpy as show below

In [23]:
a = np.outer(np.arange(10), np.arange(3))
a*a.T

ValueError: operands could not be broadcast together with shapes (10,3) (3,10) 

## Saving data and serialising